In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('play_tennis.csv')

In [3]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
data.drop(columns=['day'],inplace=True)

In [5]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

### Problem 1 
### Outlook-Sunny Temp=Hot Humidity=High, Wind = Weak 
### PLay or not
### Solution

### P(Yes | Sunny,Hot,High,Weak)
= P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)

### P(No | Sunny,Hot,High,Weak)
= P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

### Compare both probabilities

### If:
### P(Yes | X) > P(No | X)
### Then → Play = Yes

### Else:
### Play = No

### Use Maximum A Posteriori (MAP) Rule
### Choose the class with maximum posterior probability

In [7]:

#training naive bayes cretes a lookup table 
#naive reads lookup table
# testing

In [8]:
# P(Yes) P(Now)

data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [9]:
py=9/14
pn=5/14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [10]:
# column1 outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [11]:
Pon=0
Prn=2/5
Psn=3/5

Poy=4/9
Pry=3/9
Psy=2/9

In [12]:
# temperature
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [13]:
PCoolNo=1/5
PHotNo=2/5
PMildNo=2/5

PCoolYes=3/9
PHotYes=2/9
PMildYes=4/9

In [14]:
#humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [15]:
PHighNo=4/5
PNormalNo=1/5
PHighYes=3/9
PNormalYes=6/9

In [16]:
#wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [17]:
PStrongNo = 3/5
PWeakNo=2/5
PStrongYes=3/9
PWeakYes=6/9

In [21]:

# Outlook - sunny, temp=hot, hummidity=high, wind=weak
Pyes=py*Psy*PHotYes*PHighYes*PWeakYes

In [22]:
Pyes

0.007054673721340388

In [23]:
Pno=pn*Psn*PHotNo*PHighNo*PWeakNo

In [24]:
Pno

0.02742857142857143

In [25]:
# NO  > YES therefore NO