In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('customer.csv')

In [6]:
df.sample(5)

    age  gender   review education purchased
8    65  Female  Average        UG        No
37   94    Male  Average        PG       Yes
33   89  Female     Good        PG       Yes
17   22  Female     Poor        UG       Yes
2    70  Female     Good        PG        No

In [7]:
df = df.iloc[:,2:]

In [8]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
X_train

NameError: name 'X_train' is not defined

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

In [ ]:
X_train = oe.transform(X_train)

In [ ]:
X_train

In [ ]:
oe.categories_

In [ ]:
X_train

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

In [ ]:
le.classes_

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train